$(function(){
    $('#azul').click(function(){
        $('h1').css("color", "#fff")
        $('h1').css("background", "#0000CD")
        $('h1').fadeOut('fast')
        $('h1').fadeIn('fast')
        $('#mensagem')    
            .text("Cor alterada com sucesso!")
            .show('fast')
            .css("color", "#0000CD")
            .css("border", "1px solid #0000CD")
            .css("backgroundColor", "#fff")
            .css("fontWeight", "normal")
    })
    $('#rosa').click(function(){
        $('h1')
            .css("color", "#fff")
            .css("background", "#C71585")
        $('#mensagem')
            .text("Cor alterada com sucesso!")
            .css({color: '#C71585', border: '2px solid #C71585', fontWeight: 'bolder'})
            .delay(3000)
            .fadeOut('slow')
            .addClass('green')
        $('button').removeClass('orange')
    })
})